calico_url: https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml
nginx_url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.5/deploy/static/provider/cloud/deploy.yaml
cloud_image: ubuntu-22.04-server-cloudimg-amd64 #https://cloud-images.ubuntu.com/releases/
ubuntu_version: 22.04
containerd_version: 1.6.2
runc_version: 1.1.0
repo_version: 1.26 # k8s repo we'll add which was recently changed to be version specific
kubernetes_version: 1.26.13 # k8s package version we'll install
pod_cidr: 10.244.0.0/16

#############################################################################
## Uncomment for multi-master master - comment apiserver: 192.168.1.150 below
#############################################################################
apiserver: 192.168.1.202
########################################################################################
## Uncomment for multi-master with loadbalancer - comment apiserver: 192.168.1.101 above
########################################################################################
#apiserver: 192.168.1.150 #loadbalancer

ubuntu_user: darrin
ubuntu_pass: labpass1
ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVyvgaKoaLfRQLV1+2/UUsuJSClgL/jwXfaB0Dyp12a+LODIBjoFQTE6Cg4rJh3mpDS4WLj8XdJiHMHQPjat6wbv9nS454vLDRAYF/L0yTrazE7XhckoebuKMvFKlp7b/+mZZzEX9xdlCMUdBDD4KuYMI7PjfWGzsN8jGnG9Lk+GRc+HXexfnnY90+fob+6g55nx6U4oiIRvFvbXCo0o4vwRHnxr/RurL08T2wKD8Vnhn2gneiz96i1sgfKGbhBjJwtNaYJSHqpzNE5/3IVVjrhSX3COfWXnMWaZ18ZWZJZF3S/gvtb2ETFvLjsGxjFGuHpTOSw9w+PG5K0CTW0P6Fk1c0Ph6eDboj1uhjIcEhoR8ToZMlkII/VqNE5yJQiX5BuuFuKcn+K2SNfAvmPimigOG1E6edWlA89+xzGqC77G1myakVbW8sXsnwOu/Dp13QJvOFTT78TT6n6tk6KCJOeG4rpLoPYGFmDJliLFILsYiCz+ywy9Hvz7AQsnt5Cqs= darrin@matrix