# ansible-playbook -i inv/hosts.yaml plays/kvm_build_vmyaml
- name: "Build VM's"
  hosts: kvmhost
  become: yes
  gather_facts: yes
  vars:
    vm_path: "/var/lib/libvirt/images"
  tasks:
    - name: ubuntu image file exists
      stat:
        path: /var/lib/libvirt/images/base/{{ cloud_image }}.img
      register: file

    - name: 'Download Ubuntu cloud image'
      get_url:
        url: 'https://cloud-images.ubuntu.com/releases/jammy/release/{{ cloud_image }}.img'
        dest: '/var/lib/libvirt/images/base/{{ cloud_image }}.img'
      when: not file.stat.exists

    - name: 'Create local directories for images'
      file:
        path: '{{ vm_path }}/{{ item }}'
        state: directory
      with_items: "{{ groups['masters'] }}, {{ groups['workers'] }}"

    - name: 'Distribute network-config.yml'
      template:
        src: '../files/network-config.yml.j2'
        dest: '{{ vm_path }}/{{ item }}/network-config.yml'
      with_items: "{{ groups['masters'] }}, {{ groups['workers'] }}"

    - name: 'Distribute user-data.yml'
      template:
        src: '../files/user-data.yml.j2'
        dest: '{{ vm_path }}/{{ item }}/user-data.yml'
      with_items: "{{ groups['masters'] }}, {{ groups['workers'] }}"

    - name: 'Generate cidata.iso'
      command: "cloud-localds -v --network-config={{ vm_path }}/{{ item }}/network-config.yml {{ vm_path }}/{{ item }}/{{ item }}-cidata.iso {{ vm_path }}/{{ item }}/user-data.yml"
      with_items: "{{ groups['masters'] }}, {{ groups['workers'] }}"

    - name: "Create instance disk image"
      command: "sudo qemu-img create -b {{ vm_path }}/base/{{ cloud_image }}.img -f qcow2 -F qcow2 {{ vm_path }}/{{ item }}/{{ item }}.qcow2"
      with_items: "{{ groups['masters'] }}, {{ groups['workers'] }}"

    - name: "Resize instance disk image"
      command: "sudo qemu-img resize {{ vm_path }}/{{ item }}/{{ item }}.qcow2 15G"
      with_items: "{{ groups['masters'] }}, {{ groups['workers'] }}"

    - name: "Create control plane nodes"
      command: "virt-install --name={{ item }} --ram=4096 --vcpus=2 --import --disk path={{ vm_path }}/{{ item }}/{{ item }}.qcow2,format=qcow2 --disk path={{ vm_path }}/{{ item }}/{{ item }}-cidata.iso,device=cdrom --os-variant=ubuntu22.04 --network bridge=br0,model=virtio --noautoconsole"
      with_items: "{{ groups['masters'] }}"

    - name: "Create worker nodes"
      command: "virt-install --name={{ item }} --ram=2048 --vcpus=2 --import --disk path={{ vm_path }}/{{ item }}/{{ item }}.qcow2,format=qcow2 --disk path={{ vm_path }}/{{ item }}/{{ item }}-cidata.iso,device=cdrom --os-variant=ubuntu22.04 --network bridge=br0,model=virtio --noautoconsole"
      with_items: "{{ groups['workers'] }}"
