- name: 'cluster worker join'
  hosts: workers
  become: yes
  gather_facts: no
  vars:
    join_cmd: "{{ lookup('ansible.builtin.file', '../files/build_output/join_worker.txt') }}"
  tasks:
    - name: 'Create ~/.kube'
      file:
        path: '~root/.kube'
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: 'Distribute ~/.kube/config'
      copy:
        src: "../files/build_output/admin.conf"
        dest: '~root/.kube/config'

    - name: 'Set permissions on ~/.kube/config'
      file:
        path: '~root/.kube/config'
        owner: root
        group: root
        mode: 0700

    - name: 'kubeadm join'
      command: "/usr/bin/{{ join_cmd }}"

    - name: 'Label worker nodes'
      command: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker="
