- name: 'download kubectl'
  hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
    # Download directly, so we don't have to set up repositories on workstation.
    - name: 'Download kubectl'
      get_url:
        url: https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl
        dest: '/usr/local/bin'
        owner: root
        group: root
        mode: 0755
