- name: 'configure localhost'
  hosts: localhost
  become: no
  gather_facts: yes
  tasks:
    - name: 'Create ~/.kube'
      file:
        path: '{{ ansible_user_dir }}/.kube'
        state: directory
        owner: darrin
        group: darrin
        mode: 0700

    - name: 'Distribute ~/.kube/config'
      copy:
#        src: "{{ hostvars['K8S_VARIABLES']['admin_temp_path'] }}/admin.conf"
        src: '../files/build_output/admin.conf'
        dest: '{{ ansible_user_dir }}/.kube/config'

    - name: 'Set permissions on ~/.kube/config'
      file:
        path: '{{ ansible_user_dir }}/.kube/config'
        owner: darrin
        group: darrin
        mode: 0700