- name: 'configure localhost'
  hosts: localhost
  become: no
  gather_facts: yes
  tasks:
    - name: 'Create ~/.kube'
      file:
        path: '{{ ansible_user_dir }}/.kube'
        state: directory
        owner: darrin
        group: darrin
        mode: 0700

    - name: 'Distribute ~/.kube/config'
      copy:
        src: '../files/build_output/admin.conf'
        dest: '{{ ansible_user_dir }}/.kube/config'

    - name: 'Set permissions on ~/.kube/config'
      file:
        path: '{{ ansible_user_dir }}/.kube/config'
        owner: darrin
        group: darrin
        mode: 0700

    - name: 'Download kubectl'
      become: yes
      get_url:
        url: https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl
        dest: '/usr/local/bin'
        owner: root
        group: root
        mode: 0755



