# ansible-playbook -i inv/hosts.yaml plays/kvm_build_image.yaml
# it doesn't setup netplan, I already did that manually.
- name: "Build VM"
  hosts: kvmhost
  become: yes
  gather_facts: yes
  remote_user: darrin
  vars:

  tasks:
    - name: "Create build directory"
      file:
        path: "/opt/vmbuild"
        state: directory
        owner: root
        group: root
        mode: '0750'
